const statusPill={Active:'sp-active',Planned:'sp-planned',Draft:'sp-draft','In review':'sp-review',Ready:'sp-ready'};
const colorFill={blue:'fill-blue',green:'fill-green',amber:'fill-amber',teal:'fill-teal',purple:'fill-purple',coral:'fill-coral'};
const iconClass={blue:'icon-blue',green:'icon-green',amber:'icon-amber',teal:'icon-teal',purple:'icon-purple',coral:'icon-coral'};
function allSystemNames(){return[...products.map(p=>p.name),...supports.map(s=>s.name)];}
const defaultProducts=[
  {id:'rocket1',name:'Rocket — Type 1',type:'Launch vehicle · Orbital',status:'Active',icon:'🚀',color:'blue',progress:74,
   reqs:[{id:'R1-001',text:'Max payload to LEO ≥ 1200 kg',source:'Customer',requestor:'Rocket — Type 1',status:'Verified'},{id:'R1-002',text:'Stage separation reliability > 99.9%',source:'Customer',requestor:'Rocket — Type 1',status:'Verified'},{id:'R1-003',text:'Max dynamic pressure ≤ 35 kPa',source:'Engineering',requestor:'Rocket — Type 1',status:'Verified'},{id:'R1-004',text:'Thermal protection system design',source:'Customer',requestor:'Launch pad system',status:'In review'},{id:'R1-005',text:'Avionics redundancy specification',source:'Engineering',requestor:'Rocket — Type 1',status:'In review'},{id:'R1-006',text:'Launch pad interface definition',source:'Ground ops',requestor:'Launch pad system',status:'Draft'}],
   bom:[{id:'P1-001',desc:'LOX feed valve assembly',qty:2,assembly:'Stage 1 propulsion',status:'Released'},{id:'P1-002',desc:'Turbopump housing — main',qty:1,assembly:'Stage 1 propulsion',status:'Released'},{id:'P1-003',desc:'Interstage adapter ring',qty:1,assembly:'Stage interface',status:'In review'},{id:'P1-004',desc:'Avionics bay enclosure',qty:1,assembly:'Guidance system',status:'In review'},{id:'P1-005',desc:'Payload fairing half-shell',qty:2,assembly:'Fairing assembly',status:'Draft'}],
   wfDone:2,wfActive:[3,4],wfTotal:7,tests:'18/26',changes:4,
   changelog:[{dot:'#639922',title:'REQ-001 payload mass updated to 1250 kg',meta:'Mar 10, 2026 · J. Donaldson',cs:'cs-approved',label:'Approved'},{dot:'#639922',title:'Stage 1 propellant tank diameter revised',meta:'Mar 7, 2026 · A. Reyes',cs:'cs-approved',label:'Approved'},{dot:'#BA7517',title:'TPS material specification under review',meta:'Mar 12, 2026 · T. Müller',cs:'cs-pending',label:'Pending'},{dot:'#888780',title:'Launch pad interface ICD initiated',meta:'Mar 14, 2026 · A. Reyes',cs:'cs-open',label:'Open'}]},
  {id:'rocket2',name:'Rocket — Type 2',type:'Launch vehicle · Suborbital',status:'Planned',icon:'🛰',color:'green',progress:22,
   reqs:[{id:'R2-001',text:'Max altitude ≥ 100 km',source:'Customer',requestor:'Rocket — Type 2',status:'Verified'},{id:'R2-002',text:'Payload mass ≥ 200 kg',source:'Customer',requestor:'Rocket — Type 2',status:'In review'},{id:'R2-003',text:'Reusable first stage concept',source:'Engineering',requestor:'Rocket — Type 2',status:'Draft'},{id:'R2-004',text:'Launch preparation time ≤ 48 hrs',source:'Customer',requestor:'Launch pad system',status:'Draft'}],
   bom:[{id:'P2-001',desc:'First stage airframe structure',qty:1,assembly:'Stage 1',status:'Draft'}],
   wfDone:1,wfActive:[2],wfTotal:7,tests:'3/26',changes:2,
   changelog:[{dot:'#639922',title:'Initial customer requirements baselined',meta:'Feb 20, 2026 · J. Donaldson',cs:'cs-approved',label:'Approved'},{dot:'#BA7517',title:'Payload mass requirement under negotiation',meta:'Mar 11, 2026 · A. Reyes',cs:'cs-pending',label:'Pending'}]}
];
const defaultSupports=[
  {id:'launchpad',name:'Launch pad system',type:'Ground support · Main product',status:'In review',icon:'🏗',color:'amber',progress:51,supports:'Rocket Type 1, Type 2',
   reqs:[{id:'LP-001',text:'Umbilical disconnect < 200 ms before liftoff',source:'System eng.',requestor:'Rocket — Type 1',status:'Verified'},{id:'LP-002',text:'Hold-down clamp release force ≥ 500 kN',source:'System eng.',requestor:'Rocket — Type 1',status:'In review'},{id:'LP-003',text:'Flame trench water deluge capacity',source:'Ground ops',requestor:'Launch pad system',status:'Draft'}],
   bom:[{id:'LP-M001',desc:'Hold-down clamp assembly',qty:4,assembly:'Ground structure',status:'In stock'},{id:'LP-M002',desc:'Umbilical mast structure',qty:1,assembly:'Services tower',status:'On order'},{id:'LP-M003',desc:'Water deluge nozzle array',qty:24,assembly:'Flame trench',status:'TBD'}],
   interfaces:2,changes:3,
   changelog:[{dot:'#639922',title:'Hold-down clamp load case updated',meta:'Mar 9, 2026 · T. Müller',cs:'cs-approved',label:'Approved'},{dot:'#BA7517',title:'Flame trench geometry revision pending',meta:'Mar 13, 2026 · A. Reyes',cs:'cs-pending',label:'Pending'}]},
  {id:'plm',name:'Inventory / PLM',type:'Parts & lifecycle management',status:'Ready',icon:'📦',color:'teal',progress:88,supports:'all products',reqs:[],bom:[],syncPct:88,pendingSync:12,supports:'all products',reqs:[],bom:[],syncPct:88,pendingSync:12,suppliers:4,changelog:[]}
];

let products = JSON.parse(localStorage.getItem('syscore_products')) || defaultProducts;
let supports = JSON.parse(localStorage.getItem('syscore_supports')) || defaultSupports;

function saveState() {
  localStorage.setItem('syscore_products', JSON.stringify(products));
  localStorage.setItem('syscore_supports', JSON.stringify(supports));
}
const idC={};
function initC(){[...products,...supports].forEach(p=>{const n=p.reqs.map(r=>parseInt(r.id.split('-').pop())||0);idC[p.id]=n.length?Math.max(...n):0;const b=p.bom.map(x=>parseInt(x.id.split('-').pop())||0);idC[p.id+'_b']=b.length?Math.max(...b):0;});}
function rPfx(id){if(id==='launchpad')return'LP';if(id==='plm')return'PLM';if(id.startsWith('rocket'))return'R'+id.replace('rocket','');return id.slice(0,3).toUpperCase();}
function bPfx(id){if(id==='launchpad')return'LP-M';if(id==='plm')return'PLM-';if(id.startsWith('rocket'))return'P'+id.replace('rocket','')+'-';return id.slice(0,2).toUpperCase()+'-';}
function nRid(id){idC[id]=(idC[id]||0)+1;return rPfx(id)+'-'+String(idC[id]).padStart(3,'0');}
function nBid(id){idC[id+'_b']=(idC[id+'_b']||0)+1;return bPfx(id)+String(idC[id+'_b']).padStart(3,'0');}
function getE(id){return products.find(p=>p.id===id)||supports.find(s=>s.id===id);}
function allBom(){return[...products,...supports.filter(s=>s.id!=='plm')].reduce((a,p)=>a+p.bom.length,0);}
function renderHome(){renderPG();renderSG();updateBadge();}
function renderPG(){document.getElementById('product-grid').innerHTML=products.map(p=>`<div class="pcard" onclick="openDetail('${p.id}')"><div class="pcard-header"><div class="pcard-icon ${iconClass[p.color]}">${p.icon}</div><div style="flex:1"><div class="pcard-name">${p.name}</div><div class="pcard-type">${p.type}</div></div><span class="status-pill ${statusPill[p.status]}">${p.status}</span></div><div class="pcard-body"><div class="prog-labels"><span>Engineering progress</span><span>${p.progress}%</span></div><div class="prog-track"><div class="prog-fill ${colorFill[p.color]}" style="width:${p.progress}%"></div></div></div><div class="qstats"><div class="qstat"><div class="qstat-val">${p.reqs.length}</div><div class="qstat-lbl">Requirements</div></div><div class="qstat"><div class="qstat-val">${p.changes}</div><div class="qstat-lbl">Open changes</div></div><div class="qstat"><div class="qstat-val">${p.tests||'—'}</div><div class="qstat-lbl">Tests passed</div></div></div><div class="pcard-footer"><span class="open-btn">Open detail →</span><div class="wdots">${wfDots(p.wfDone,p.wfActive,p.wfTotal)}</div></div></div>`).join('');}
function renderSG(){document.getElementById('support-grid').innerHTML=supports.map(s=>{const s1=s.id==='plm'?`<div class="scard-stat"><div class="scard-stat-val">${allBom()}</div><div class="scard-stat-lbl">BOM lines</div></div>`:`<div class="scard-stat"><div class="scard-stat-val">${s.reqs.length}</div><div class="scard-stat-lbl">Requirements</div></div>`;const s2=s.id==='plm'?`<div class="scard-stat"><div class="scard-stat-val">${s.pendingSync}</div><div class="scard-stat-lbl">Pending sync</div></div>`:`<div class="scard-stat"><div class="scard-stat-val">${s.changes||0}</div><div class="scard-stat-lbl">Open changes</div></div>`;const s3=s.id==='plm'?`<div class="scard-stat"><div class="scard-stat-val">${s.suppliers}</div><div class="scard-stat-lbl">Suppliers</div></div>`:`<div class="scard-stat"><div class="scard-stat-val">${s.bom.length}</div><div class="scard-stat-lbl">Components</div></div>`;const pl=s.id==='plm'?'Sync status':'Readiness';return`<div class="scard" onclick="openDetail('${s.id}')"><div class="scard-inner"><div class="scard-accent acc-${s.color}"></div><div style="flex:1;display:flex;flex-direction:column"><div class="scard-content"><div class="scard-top"><div class="scard-icon ${iconClass[s.color]}">${s.icon}</div><div style="flex:1"><div class="scard-name">${s.name}</div><div class="scard-sub">${s.type}</div></div><span class="status-pill ${statusPill[s.status]}">${s.status}</span></div><div><div class="prog-labels"><span>${pl}</span><span>${s.progress}%</span></div><div class="prog-track"><div class="prog-fill ${colorFill[s.color]}" style="width:${s.progress}%"></div></div></div><div class="scard-row">${s1}${s2}${s3}</div></div><div class="scard-footer"><span>Supports: ${s.supports}</span><span class="open-btn">Open detail →</span></div></div></div></div>`;}).join('');}
function wfDots(done,active,total){let h='';for(let i=1;i<=total;i++){let c='open';if(i<=done)c='done';else if(active&&active.includes(i))c='active';h+=`<div class="wdot ${c}"></div>`;}return h;}
function updateBadge(){const n=[...products,...supports].flatMap(p=>p.reqs).filter(r=>r.status==='In review').length;document.getElementById('review-badge').textContent=`${n} review${n!==1?'s':''} pending`;}
function openDetail(id){
  const e=getE(id),isS=supports.some(s=>s.id===id);
  document.getElementById('detail-header').innerHTML=`<div class="detail-icon ${iconClass[e.color]}">${e.icon}</div><div><div class="detail-title">${e.name}</div><div class="detail-sub">${e.type} · <span class="status-pill ${statusPill[e.status]}">${e.status}</span></div></div><div class="detail-header-stats">${id==='plm'?`<div class="dhs"><div class="dhs-val" id="dh-plm-bom">${allBom()}</div><div class="dhs-lbl">BOM lines</div></div><div class="dhs"><div class="dhs-val">${e.progress}%</div><div class="dhs-lbl">Sync</div></div><div class="dhs"><div class="dhs-val">${e.pendingSync}</div><div class="dhs-lbl">Pending sync</div></div><div class="dhs"><div class="dhs-val">${e.suppliers}</div><div class="dhs-lbl">Suppliers</div></div>`:`<div class="dhs"><div class="dhs-val">${e.progress}%</div><div class="dhs-lbl">Progress</div></div><div class="dhs"><div class="dhs-val" id="dh-req">${e.reqs.length}</div><div class="dhs-lbl">Requirements</div></div>${!isS?`<div class="dhs"><div class="dhs-val">${e.tests||'—'}</div><div class="dhs-lbl">Tests</div></div>`:''}<div class="dhs"><div class="dhs-val" id="dh-bom">${e.bom.length}</div><div class="dhs-lbl">Components</div></div>`}</div>`;
  let tabs='',panels='';
  if(id==='plm'){tabs+=tb('plm','bom','BOM / Components',true);tabs+=tb('plm','requirements','Requirements');tabs+=tb('plm','suppliers','Suppliers');panels+=`<div id="tp-plm-bom" class="tab-panel tab-content active">${buildPLMBom()}</div>`;panels+=`<div id="tp-plm-requirements" class="tab-panel tab-content">${buildReq('plm')}</div>`;panels+=`<div id="tp-plm-suppliers" class="tab-panel tab-content">${buildSupp()}</div>`;}
  else if(isS){tabs+=tb(id,'workflow','Workflow',true);tabs+=tb(id,'requirements',`Requirements <span class="tab-count">${e.reqs.length}</span>`);tabs+=tb(id,'bom','Components / BOM');tabs+=tb(id,'changelog','Data & changes');panels+=`<div id="tp-${id}-workflow" class="tab-panel tab-content active">${buildWf(e)}</div>`;panels+=`<div id="tp-${id}-requirements" class="tab-panel tab-content">${buildReq(id)}</div>`;panels+=`<div id="tp-${id}-bom" class="tab-panel tab-content">${buildBom(id)}</div>`;panels+=`<div id="tp-${id}-changelog" class="tab-panel tab-content">${buildCL(e)}</div>`;}
  else{tabs+=tb(id,'workflow','Workflow',true);tabs+=tb(id,'requirements',`Requirements <span class="tab-count">${e.reqs.length}</span>`);tabs+=tb(id,'bom','Components / BOM');tabs+=tb(id,'changelog','Data & changes');tabs+=tb(id,'qualification','Qualification');panels+=`<div id="tp-${id}-workflow" class="tab-panel tab-content active">${buildWf(e)}</div>`;panels+=`<div id="tp-${id}-requirements" class="tab-panel tab-content">${buildReq(id)}</div>`;panels+=`<div id="tp-${id}-bom" class="tab-panel tab-content">${buildBom(id)}</div>`;panels+=`<div id="tp-${id}-changelog" class="tab-panel tab-content">${buildCL(e)}</div>`;panels+=`<div id="tp-${id}-qualification" class="tab-panel tab-content">${buildQual()}</div>`;}
  document.getElementById('detail-tabs').innerHTML=tabs;
  document.getElementById('detail-tab-panels').innerHTML=panels;
  document.getElementById('breadcrumb').innerHTML=`<span class="bc-link" onclick="goHome()">Products</span><span class="bc-sep">›</span><span class="bc-current">${e.name}</span>`;
  document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));
  document.getElementById('page-detail').classList.add('active');
  window.scrollTo(0,0);}
function tb(pid,tab,label,active){return`<button class="tab-btn${active?' active':''}" onclick="switchTab('${pid}','${tab}')">${label}</button>`;}
function buildWf(e){const labels=['Customer<br>requirements','Specifications &amp;<br>req. mgmt','Data base &amp;<br>change mgmt','BOM, ICD &amp;<br>specifications','Inventory &amp;<br>PLM','Qualification &amp;<br>testing','Requirements<br>meeting'];const total=e.wfTotal||7;let s='';for(let i=1;i<=total;i++){let c='open',l=i;if(i<=e.wfDone){c='done';l='✓';}else if(e.wfActive&&e.wfActive.includes(i))c='active';s+=`<div class="wf-step"><div class="wf-node ${c}">${l}</div><div class="wf-label">${labels[i-1]||'Step '+i}</div></div>`;}return`<div class="workflow-steps">${s}</div><div class="wf-hint">Active steps: ${e.wfActive?e.wfActive.join(', '):'—'}</div>`;}
function sC(s){return s==='Verified'?'st-verified':s==='In review'?'st-review':'st-draft';}
function bC(s){return s==='Released'?'st-released':s==='In review'?'st-review':s==='In stock'?'st-instock':s==='On order'?'st-onorder':s==='TBD'?'st-tbd':'st-draft';}
function buildReq(id){
  const e=getE(id);
  const rows=e.reqs.length?e.reqs.map(r=>`<tr><td class="mono">${r.id}</td><td>${r.text}</td><td style="white-space:nowrap;font-size:11px;color:#9c9a92">${r.source}</td><td><span class="requestor-tag">${r.requestor||'—'}</span></td><td><span class="req-status ${sC(r.status)}">${r.status}</span></td></tr>`).join(''):`<tr><td colspan="5" class="empty-state" style="padding:24px 0">No requirements yet — add one below.</td></tr>`;
  const reqOpts=allSystemNames().map(n=>`<option value="${n}">${n}</option>`).join('');
  return`<table class="req-table"><thead><tr><th style="width:84px">ID</th><th>Requirement</th><th style="width:96px">Source</th><th style="width:130px">Requestor</th><th style="width:86px">Status</th></tr></thead><tbody id="rb-${id}">${rows}</tbody></table>
    <div class="add-bar">
      <input type="text" id="ri-${id}" placeholder="Add a new requirement…" onkeydown="if(event.key==='Enter')addR('${id}')"/>
      <select id="rs-${id}" title="Source"><option value="">Source…</option><option>Customer</option><option>Engineering</option><option>Ground ops</option><option>System eng.</option></select>
      <select id="rreq-${id}" title="Requestor — which system is requesting this"><option value="">Requestor…</option>${reqOpts}</select>
      <select id="rst-${id}"><option value="Draft">Draft</option><option value="In review">In review</option><option value="Verified">Verified</option></select>
      <button class="btn-primary" onclick="addR('${id}')">+ Add</button>
    </div>
    <div style="font-size:10px;color:#b0aea6;margin-top:6px">↗ Requestor = which system is requesting this requirement</div>`;}
function buildBom(id){const e=getE(id);const rows=e.bom.length?e.bom.map(b=>`<tr><td class="mono">${b.id}</td><td>${b.desc}</td><td style="font-weight:500;color:#1a1a18">${b.qty}</td><td style="font-size:12px;color:#6b6b67">${b.assembly||'—'}</td><td><span class="req-status ${bC(b.status)}">${b.status}</span></td></tr>`).join(''):`<tr><td colspan="5" class="empty-state" style="padding:24px 0">No components yet — add one below.</td></tr>`;return`<div class="tab-section-title">Component list (BOM)</div><table class="data-table"><thead><tr><th style="width:88px">Part no.</th><th>Description</th><th style="width:48px">Qty</th><th>Assembly / system</th><th style="width:90px">Status</th></tr></thead><tbody id="bb-${id}">${rows}</tbody></table><div class="add-bar"><input type="text" id="bd-${id}" placeholder="Component description…" onkeydown="if(event.key==='Enter')addB('${id}')"/><input type="number" id="bq-${id}" placeholder="Qty" style="width:60px;min-width:60px" min="1" value="1"/><input type="text" id="ba-${id}" placeholder="Assembly / system" style="width:140px;min-width:90px"/><select id="bs-${id}"><option value="Draft">Draft</option><option value="In review">In review</option><option value="Released">Released</option><option value="In stock">In stock</option><option value="On order">On order</option></select><button class="btn-primary" onclick="addB('${id}')">+ Add</button></div>`;}
function buildPLMBom(){const all=[...products,...supports.filter(s=>s.id!=='plm')];let h='';all.forEach(e=>{const rows=e.bom.length?e.bom.map(b=>`<tr><td class="mono">${b.id}</td><td>${b.desc}</td><td style="font-weight:500;color:#1a1a18">${b.qty}</td><td style="font-size:12px;color:#6b6b67">${b.assembly||'—'}</td><td><span class="req-status ${bC(b.status)}">${b.status}</span></td></tr>`).join(''):`<tr><td colspan="5" style="padding:8px 0;font-size:11px;color:#9c9a92;font-style:italic">No components</td></tr>`;h+=`<div class="plm-product-block"><div class="plm-block-header"><div class="plm-block-icon ${iconClass[e.color]}">${e.icon}</div>${e.name}<span style="margin-left:auto;font-size:11px;color:#9c9a92;font-weight:400" id="plmc-${e.id}">${e.bom.length} components</span></div><table class="data-table" style="margin-top:0"><thead><tr><th style="width:88px">Part no.</th><th>Description</th><th style="width:48px">Qty</th><th>Assembly</th><th style="width:90px">Status</th></tr></thead><tbody id="pb-${e.id}">${rows}</tbody></table><div class="add-bar" style="margin-bottom:8px"><input type="text" id="pd-${e.id}" placeholder="Add component to ${e.name}…" onkeydown="if(event.key==='Enter')addBP('${e.id}')"/><input type="number" id="pq-${e.id}" placeholder="Qty" style="width:60px;min-width:60px" min="1" value="1"/><select id="ps-${e.id}"><option value="Draft">Draft</option><option value="In review">In review</option><option value="Released">Released</option><option value="In stock">In stock</option><option value="On order">On order</option></select><button class="btn-primary" onclick="addBP('${e.id}')">+ Add</button></div></div>`;});return`<div class="tab-section-title">BOM by product</div>${h}`;}
function buildSupp(){return`<table class="data-table"><thead><tr><th>Supplier</th><th>Parts supplied</th><th>Lead time</th><th>Status</th></tr></thead><tbody><tr><td class="strong-cell">Aerojet Systems</td><td>Turbopump, valves</td><td>16 weeks</td><td><span class="req-status st-verified">Active</span></td></tr><tr><td class="strong-cell">SteelForm GmbH</td><td>Structural rings, adapters</td><td>10 weeks</td><td><span class="req-status st-verified">Active</span></td></tr><tr><td class="strong-cell">AvioElect Ltd</td><td>Avionics enclosures</td><td>8 weeks</td><td><span class="req-status st-review">Review</span></td></tr><tr><td class="strong-cell">CompThermal AS</td><td>TPS panels, fairing</td><td>20 weeks</td><td><span class="req-status st-draft">Onboarding</span></td></tr></tbody></table>`;}
function buildCL(e){if(!e.changelog||!e.changelog.length)return`<div class="empty-state">No changes logged yet.</div>`;return`<div class="tab-section-title">Change log</div>`+e.changelog.map(c=>`<div class="change-row"><div class="change-dot" style="background:${c.dot}"></div><div class="change-body"><div class="change-title">${c.title}</div><div class="change-meta">${c.meta}</div></div><span class="cs ${c.cs}">${c.label}</span></div>`).join('');}
function buildQual(){return`<div class="dstat-row"><div class="dstat"><div class="dstat-val">18</div><div class="dstat-lbl">Tests passed</div></div><div class="dstat"><div class="dstat-val">5</div><div class="dstat-lbl">In progress</div></div><div class="dstat"><div class="dstat-val">3</div><div class="dstat-lbl">Not started</div></div><div class="dstat"><div class="dstat-val">68%</div><div class="dstat-lbl">Coverage</div></div></div><div class="qual-grid"><div class="qual-item"><div class="qual-name">Vibration & acoustic testing</div><div class="qual-meta">Stage 1 · Completed Mar 5</div><div class="qual-bar-track"><div class="qual-bar-fill fill-green" style="width:100%"></div></div></div><div class="qual-item"><div class="qual-name">Thermal vacuum cycling</div><div class="qual-meta">Avionics bay · In progress</div><div class="qual-bar-track"><div class="qual-bar-fill fill-blue" style="width:60%"></div></div></div><div class="qual-item"><div class="qual-name">Stage separation test</div><div class="qual-meta">Interstage · Completed Feb 28</div><div class="qual-bar-track"><div class="qual-bar-fill fill-green" style="width:100%"></div></div></div><div class="qual-item"><div class="qual-name">Propellant feed system proof</div><div class="qual-meta">Stage 1 · In progress</div><div class="qual-bar-track"><div class="qual-bar-fill fill-blue" style="width:45%"></div></div></div></div>`;}
function addR(id){const inp=document.getElementById('ri-'+id);const src=document.getElementById('rs-'+id).value||'—';const req=document.getElementById('rreq-'+id).value||'—';const st=document.getElementById('rst-'+id).value;const txt=inp.value.trim();if(!txt){inp.focus();return;}const e=getE(id),r={id:nRid(id),text:txt,source:src,requestor:req,status:st};e.reqs.push(r);inp.value='';const tb=document.getElementById('rb-'+id);if(tb){const tr=document.createElement('tr');tr.innerHTML=`<td class="mono">${r.id}</td><td>${r.text}</td><td style="white-space:nowrap;font-size:11px;color:#9c9a92">${r.source}</td><td><span class="requestor-tag">${r.requestor}</span></td><td><span class="req-status ${sC(r.status)}">${r.status}</span></td>`;if(tb.querySelector('td[colspan]'))tb.innerHTML='';tb.appendChild(tr);tr.scrollIntoView({behavior:'smooth',block:'nearest'});}const tc=document.querySelector('#detail-tabs .tab-btn[onclick*="requirements"] .tab-count');if(tc)tc.textContent=e.reqs.length;const dh=document.getElementById('dh-req');if(dh)dh.textContent=e.reqs.length;updateBadge();saveState();renderHome();}
function addB(id){const d=document.getElementById('bd-'+id),q=document.getElementById('bq-'+id),a=document.getElementById('ba-'+id),s=document.getElementById('bs-'+id);const desc=d.value.trim();if(!desc){d.focus();return;}const e=getE(id),item={id:nBid(id),desc,qty:parseInt(q.value)||1,assembly:a.value.trim()||'—',status:s.value};e.bom.push(item);d.value='';q.value='1';a.value='';const tb=document.getElementById('bb-'+id);if(tb){const tr=document.createElement('tr');tr.innerHTML=`<td class="mono">${item.id}</td><td>${item.desc}</td><td style="font-weight:500;color:#1a1a18">${item.qty}</td><td style="font-size:12px;color:#6b6b67">${item.assembly}</td><td><span class="req-status ${bC(item.status)}">${item.status}</span></td>`;if(tb.querySelector('td[colspan]'))tb.innerHTML='';tb.appendChild(tr);tr.scrollIntoView({behavior:'smooth',block:'nearest'});}const dhb=document.getElementById('dh-bom');if(dhb)dhb.textContent=e.bom.length;saveState();renderHome();}
function addBP(pid){const d=document.getElementById('pd-'+pid),q=document.getElementById('pq-'+pid),s=document.getElementById('ps-'+pid);const desc=d.value.trim();if(!desc){d.focus();return;}const e=getE(pid),item={id:nBid(pid),desc,qty:parseInt(q.value)||1,assembly:'—',status:s.value};e.bom.push(item);d.value='';q.value='1';const tb=document.getElementById('pb-'+pid);if(tb){const tr=document.createElement('tr');tr.innerHTML=`<td class="mono">${item.id}</td><td>${item.desc}</td><td style="font-weight:500;color:#1a1a18">${item.qty}</td><td style="font-size:12px;color:#6b6b67">—</td><td><span class="req-status ${bC(item.status)}">${item.status}</span></td>`;if(tb.querySelector('td[colspan]'))tb.innerHTML='';tb.appendChild(tr);const hdr=document.getElementById('plmc-'+pid);if(hdr)hdr.textContent=e.bom.length+' components';tr.scrollIntoView({behavior:'smooth',block:'nearest'});}const dplm=document.getElementById('dh-plm-bom');if(dplm)dplm.textContent=allBom();saveState();renderHome();}
function goHome(){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-home').classList.add('active');document.getElementById('breadcrumb').innerHTML='<span class="bc-current">Products</span>';renderHome();window.scrollTo(0,0);}
function switchTab(pid,tab){document.querySelectorAll('#detail-tabs .tab-btn').forEach(b=>b.classList.remove('active'));document.querySelectorAll('#detail-tab-panels .tab-content').forEach(c=>c.classList.remove('active'));const p=document.getElementById(`tp-${pid}-${tab}`);if(p)p.classList.add('active');document.querySelectorAll('#detail-tabs .tab-btn').forEach(b=>{if(b.getAttribute('onclick')&&b.getAttribute('onclick').includes(`'${tab}'`))b.classList.add('active');});}
const mE={mp:'🚀',ms:'🏗'},mC={mp:'blue',ms:'amber'};
function openModal(t){document.getElementById('modal-'+t).classList.add('open');}
function closeModal(t){document.getElementById('modal-'+t).classList.remove('open');}
document.querySelectorAll('.modal-overlay').forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('open');}));
function pickEmoji(p,el){document.querySelectorAll(`#${p}-emoji-row .emoji-opt`).forEach(e=>e.classList.remove('selected'));el.classList.add('selected');mE[p]=el.dataset.e;}
function pickColor(p,el){document.querySelectorAll(`#${p}-color-row .color-opt`).forEach(e=>e.classList.remove('selected'));el.classList.add('selected');mC[p]=el.dataset.c;}
function submitProduct(){const name=document.getElementById('mp-name').value.trim(),type=document.getElementById('mp-type').value.trim(),status=document.getElementById('mp-status').value;if(!name){document.getElementById('mp-name').focus();return;}const id='prod_'+Date.now();products.push({id,name,type:type||'Product',status,icon:mE.mp,color:mC.mp,progress:0,reqs:[],bom:[],wfDone:0,wfActive:[],wfTotal:7,tests:'0/0',changes:0,changelog:[]});idC[id]=0;idC[id+'_b']=0;document.getElementById('mp-name').value='';document.getElementById('mp-type').value='';closeModal('product');saveState();renderHome();}
function submitSupport(){const name=document.getElementById('ms-name').value.trim(),type=document.getElementById('ms-type').value.trim(),status=document.getElementById('ms-status').value,sup=document.getElementById('ms-supports').value.trim();if(!name){document.getElementById('ms-name').focus();return;}const id='supp_'+Date.now();supports.push({id,name,type:type||'Support system',status,icon:mE.ms,color:mC.ms,progress:0,supports:sup||'all products',reqs:[],bom:[],interfaces:0,changes:0,changelog:[]});idC[id]=0;idC[id+'_b']=0;document.getElementById('ms-name').value='';document.getElementById('ms-type').value='';document.getElementById('ms-supports').value='';closeModal('support');saveState();renderHome();}
initC();renderHome();
